### ISSUE TITLE
Furigana spacing, missing import

### ISSUE THREAD

**Issue by kaieberl** [waldeir/pandoc-filter-furigana#1]
Great idea to develop this! I had to fix 2 issues to make it work.
You might want to add this code to a template.tex that is additionally passed in via `--template=japanese-template.tex`.

```
\usepackage{ruby}

% Adjust the vertical spacing
\renewcommand{\rubysep}{0ex}
```

**Comment by waldeir** [comment]
You can pass these two arguments with the -V option, like this

`pandoc -F handleFurigana.py -t latex --pdf-engine=lualatex -V documentclass=ltjarticle  -V header-includes:'\usepackage{ruby}' -V '\renewcommand{\rubysep}{0ex}' -i myfile.md -o myfile.pdf`

Didn't it work on your system?

**Comment by kaieberl** [comment]
Oh sorry, I had overlooked that part. Yes that works perfectly 👍🏻
